on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
 
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run: deno install
      - run: deno task format:check
        name: Check Format
      - run: deno task lint
        name: Lint
